apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "challengercluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "challengercluster"
    spec:
      containers:
        - name: "challengercluster"
          image: "akseshopper.azurecr.io/challengercluster"
          ports:
          - containerPort: 80